### PR TITLE
Readme: fixed doc link

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by hrach** [comment]
I would prefer migrating doc to this repo like in orm / dbal :))

**Comment by TomasVotruba** [comment]
You mean here? http://nextras.cz/datagrid/docs

**Comment by hrach** [comment]
Yeah, see ORM repo for structure.

**Comment by TomasVotruba** [comment]
I see. I might look at it later.

**Comment by TomasVotruba** [comment]
Closing due to too much effort for me ATM.

**Pull request closed without merging**
