### PR TITLE
composer: allow PHP 7

### PR DESCRIPTION
**Pull request by TomasVotruba**
Also wondering, would you care for some tests? If so, would you be ok with PHPUnit?

### CODE REVIEW

**Comment by hrach** [comment]
Datagried requires quite big refactoring. Personally I would like to stick with nette tester

**Comment by hrach** [comment]
Thank you!

**Comment by TomasVotruba** [comment]
Not sure what it means. Should I wait for refactoring then?

**Comment by TomasVotruba** [comment]
:+1:

**Comment by hrach** [comment]
> Not sure what it means. Should I wait for refactoring then?

Dunno. Honestly, I have no time to do it. Right know, datagrid is quite buggy, see forum thread...it is needed to fix it,test is, and this will probably invole some refactoring.

**Pull request merged**
