### PR TITLE
added array getter

### PR DESCRIPTION
**Pull request by MartkCz**

### CODE REVIEW

**Comment by matej21** [comment]
preferring array access over an object access could be a bc break (when offsetGet($foo) returns something else than ->{$foo})

**Comment by MartkCz** [comment]
Oh, you're right, what about this?

```php
if (!isset($row->$column)) {
	if (is_array($row) || $row instanceof \ArrayAccess) {
		return $row[$column];
	}

	if ($need) {
		throw new \InvalidArgumentException("Result row does not have '{$column}' column.");
	} else {
		return null;
	}
}

return $row->$column;
```

**Comment by matej21** [comment]
:+1: with a small fix:
```php
if ((is_array($row) || $row instanceof \ArrayAccess) && isset($row[$column])) {
```

**Comment by hrach** [comment]
Thanks pro PR & review!

**Pull request merged**
